### ISSUE TITLE
More info available?

### ISSUE THREAD

**Issue by shmick** [sterlingwes/eurobot#1]
Hi,

Looking for something to post euro 2016 scores into slack as well. Any more info on how to get this up and running?

Thanks.

**Comment by sterlingwes** [comment]
@shmick I'll look at throwing together a readm. Would need some rejigging as it stands as I've been experimenting with the API. Doesn't appear the webhook events work, so I'm trying polling.

In the interim you can add a twitter integration for [@LiveEuroScores](https://twitter.com/LiveEuroScores) which is getting the same updates.

**Comment by sterlingwes** [comment]
added a readme

**Comment by shmick** [comment]
Thanks. I've got it up and running now.

Cheers.

**Comment by sterlingwes** [comment]
@shmick made some updates FYI
